(define-library (r7rs-extras all)
  (import (r7rs-extras higher-order))
  (include-library-declarations "higher-order.exports.scm")
  (import (r7rs-extras io))
  (include-library-declarations "io.exports.scm")
  (import (r7rs-extras partition))
  (include-library-declarations "partition.exports.scm")
  (import (r7rs-extras arithmetic))
  (include-library-declarations "arithmetic.exports.scm")
  )
